### ISSUE TITLE
namespace load failed.

### ISSUE THREAD

**Issue by batis2ta** [barkasn/nbHelpers#2]
Dear people, I tried to install nbHelpers with install_github("barkasn/nbHelpers") unfortunately i face an error. Is there work around for this?

installing *source* package ‘nbHelpers’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘nbHelpers’ in namespaceExport(ns, exports):
 undefined exports: read10xmatrices, readMultiple10Xmatrices
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by barkasn** [comment]
Thank you for pointing this out it has now been fixed with commit 26ed8a2
